export enum Routes {
  // SCREENS
  PROFILE = 'Profile',
  WELCOME = 'Welcome',
  HOME = 'Home',
  UPCOMINGMEETINGS = 'Upcoming Meetings',
  PREVIOUSMEETINGS = 'Previous Meetings',
  MEETINGRECORDINGS = 'Meeting Recordings',
  SCHEDULEMEETING = 'Schedule Meeting',
  JOINMEETING = 'Join Meeting',
  NEWMEETING = 'New Meeting',
  VIDEOPLAYER = 'Video',
  CALL = 'Call',
  CALLSETUP = 'Call Setup',
  CALLENDED = 'Call Ended',
  AUTH = 'Auth',
  VERIFY = 'Verify',
  USERLIST = 'Users',
  // NAVIGATION
  AUTHSTACK = 'AuthStack',
  AUTHENTICATEDSTACK = 'AuthenticatedStack',
  CALLSTACK = 'CallStack',
  MAINTABS = 'MainTabs',
  MEETINGSTACK = 'MeetingStack',
}
